### ISSUE TITLE
下载器报错

### ISSUE THREAD

**Issue by wx24736** [Hyper-Beast/91porn#1]
m3u8下载器报错

**Comment by Hyper-Beast** [comment]
由于我的疏忽代码里面把history写成histoy了，你自己创建一个histoy和history文件就行了（都没有后缀）

**Comment by Hyper-Beast** [comment]
> m3u8下载器报错

修复了，下载覆盖就可以了

**Comment by wx24736** [comment]
![image](https://user-images.githubusercontent.com/41844950/126288588-ff6621e0-0312-4dc1-85e9-0a26594d8c6f.png)
提示进程被另一程序占用

**Comment by wx24736** [comment]
可以了，是我进程没关闭

**Comment by wx24736** [comment]
删除原来的文件，重新覆盖重启解决了
