### ISSUE TITLE
未能找到文件 m3u8url.txt

### ISSUE THREAD

**Issue by paopaogn** [Hyper-Beast/91porn#12]
显示错误 未能找到文件 m3u8url.txt
![cuowu](https://user-images.githubusercontent.com/46473933/156564444-bfdcfa54-6eaf-456b-9609-350a6325e1a2.jpg)

**Comment by Hyper-Beast** [comment]
解析下载地址失败了，url那个文件正常吗，有没有正常获取到url

**Comment by paopaogn** [comment]
> 解析下载地址失败了，url那个文件正常吗，有没有正常获取到url
![Inkedcw_LI](https://user-images.githubusercontent.com/46473933/157043009-ce189b79-41df-428e-8a37-1a5338ff6b28.jpg)

无法正常获取到url

**Comment by Hyper-Beast** [comment]
> > 解析下载地址失败了，url那个文件正常吗，有没有正常获取到url
> > ![Inkedcw_LI](https://user-images.githubusercontent.com/46473933/157043009-ce189b79-41df-428e-8a37-1a5338ff6b28.jpg)
> 
> 无法正常获取到url

我测试了目前为止还是一切正常，确保你能访问91porn.com这个网站，或者自己去改地址为807那个
![image](https://user-images.githubusercontent.com/18001712/157045584-4b198af8-7170-4ff3-bd94-bd0ae5bcc171.png)
