### ISSUE TITLE
m3u8url.txt

### ISSUE THREAD

**Issue by wub16** [Hyper-Beast/91porn#2]
求助大神，没办法生成m3u8url.txt怎么弄啊?url.txt里面有链接，运行downloadm3u8.py没有报错，但无法生成m3u8url.txt

**Comment by Hyper-Beast** [comment]
url.txt里的那些链接你能正常访问吗

**Comment by wx24736** [comment]
确实不能生成txt文件了

**Comment by Hyper-Beast** [comment]
> 确实不能生成txt文件了

已修复，重新下载下downloadm3u8.py替换原来的就行了
