### ISSUE TITLE
NameError: name 'response' is not defined

### ISSUE THREAD

**Issue by yeqi01** [Hyper-Beast/91porn#5]
======== RESTART: C:\Users\XXXXXX\Documents\GitHub\91porn\downloadm3u8.py ========
https://820.xxxxxxxxx.live/view_video.php?viewkey=5704c066ca947ed6e99b&page=41&viewtype=basic&category=rf

Traceback (most recent call last):
  File "C:\Users\5490\Documents\GitHub\91porn\downloadm3u8.py", line 19, in <module>
    f.write(response.text)
NameError: name 'response' is not defined

**Comment by yeqi01** [comment]
如何解决？我是WIN10

**Comment by yeqi01** [comment]
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Confirm</title>
    </head>
    <body>
    <table width=600 align=center><tr><td>
 <b><img src="images/logo.png" alt="自拍论坛" border="0" /><br><br><font >请点击以下链接访问，以验证你不是机器人！</font></b>

    <br>
          <a href="https://820.xxxxxxxxxxxxx.live/view_video.php?viewkey=d043c467915b313a716d&amp;page=81&amp;viewtype=basic&amp;category=rf%0A">https://820.workarea7.live/view_video.php?viewkey=d043c467915b313a716d&amp;page=81&amp;viewtype=basic&amp;category=rf%0A</a>
    <br> <br> <br>	
   
   这个是什么原因？
   
  </td></tr></table>
</html>

**Comment by Hyper-Beast** [comment]
cookie设置了吗，抓下自己的cookie填到脚本里

**Comment by Hyper-Beast** [comment]
> ```
>   <head>
> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
>     <title>Confirm</title>
> </head>
> <body>
> <table width=600 align=center><tr><td>
> ```
> 
> ![自拍论坛](images/logo.png)请点击以下链接访问，以验证你不是机器人！
> 
> ```
> <br>
>       <a href="https://820.xxxxxxxxxxxxx.live/view_video.php?viewkey=d043c467915b313a716d&amp;page=81&amp;viewtype=basic&amp;category=rf%0A">https://820.workarea7.live/view_video.php?viewkey=d043c467915b313a716d&amp;page=81&amp;viewtype=basic&amp;category=rf%0A</a>
> <br> <br> <br>	
> ```
> 
> 这个是什么原因？

测试了目前加上自己的cookie还是正常的，脚本没问题
