### ISSUE TITLE
任意键

### ISSUE THREAD

**Issue by karlkeuler** [Hyper-Beast/91porn#6]
![image](https://user-images.githubusercontent.com/78457823/136558942-a3a25a41-8d36-4a87-8b4a-9f889ae48dca.png)
按了任意键之后就退出了。。。没有进一步实行啊

**Comment by Hyper-Beast** [comment]
> ![image](https://user-images.githubusercontent.com/78457823/136558942-a3a25a41-8d36-4a87-8b4a-9f889ae48dca.png) 按了任意键之后就退出了。。。没有进一步实行啊

直接双击运行.bat执行不要去跑这些py脚本

**Comment by karlkeuler** [comment]
这个界面就是双击.bat的结果，然后按任意键之后就什么都没有反应了
